ALTER TABLE site_settings
ADD COLUMN IF NOT EXISTS notice_enabled BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS notice_text TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS notice_speed INT NOT NULL DEFAULT 60;

